name: revold
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - descartes
  - python=3.7
  - colorama
  - geopandas
  - pandas
  - numpy
  #- rasterio
  - h5py
  # - gdal
  # - dask
  - nrel-rev=0.4.38
  - nrel-pysam=2.2.0
  - nrel-rex=0.2.36
  - nrel-revx=0.3.9
  - ipython
  - xlrd
  - xlsxwriter
  # - spyder
  - tabulate
  - tqdm
  - pip
  - pip:
    - addfips
    - cpi
    - pgpasslib
    - h5pyd
    - pandarallel
    - ipywidgets
    - pathos
