name: homeruns
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - colorama
  - descartes
  - gdal
  - geopandas
  - h5py
  - ipython
  - numpy
  - pandas
  - rasterio
  - rioxarray
  - tabulate
  - tqdm
  - xarray
  - xlrd
  - xlsxwriter
  - pip
  - pip:
    - addfips
    - cpi
    - pgpasslib
    - pathos
    - h5pyd
    - pandarallel
    - ipywidgets
    - pathos
    - openpyxl
    - HOPP=0.0.5
