name: revruns
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - descartes
  - python=3.7
  - colorama
  - geopandas
  - pandas
  - numpy
  - rasterio
  - h5py
  - gdal
  - dask
  - nrel-rev
  - nrel-pysam
  - nrel-rex
  - nrel-revx
  - ipython
  - xlrd
  - xlsxwriter
  - spyder
  - tabulate
  - tqdm
  - pip
  - pip:
    - cpi
    - pgpasslib
    - h5pyd
    - pandarallel
    - ipywidgets
    - pathos
