name: revruns
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - descartes
  - python=3.8
  - colorama
  - geopandas
  - pandas
  - numpy
  - rasterio
  - h5py
  - gdal
  - dask
  - ipython
  - xlrd
  - xlsxwriter
  - spyder
  - tabulate
  - tqdm
  - pip
  - pip:
    - addfips
    - cpi
    - pgpasslib
    - pathos
    - h5pyd
    - pandarallel
    - ipywidgets
    - pathos
    - openpyxl
